[package]
name = "rs_pwstore"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = ">=0.25.3"
magic-crypt = ">=3.0.0"
